name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Install nightly yosys, nextpnr
      - uses: actions/checkout@v2
      - uses: YosysHQ/setup-oss-cad-suite@v1
      - run: yosys --version
      - run: nextpnr-ecp5 --version

      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install Tools
      - name: Install Tools
        run: |
          sudo apt-get install wget build-essential python3
          python3 -m venv env
          source env/bin/activate
          pip3 install --upgrade pip
          pip3 install setuptools
          pip3 install requests

      # Install LiteX + toolchains
      - name: Install LiteX
        run: |
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          source env/bin/activate
          python3 litex_setup.py --config=full --init --install --user
          python3 litex_setup.py --gcc=riscv
          ls $PWD/../riscv64-*/bin/
          export PATH=$PATH:$(echo $PWD/../riscv64-*/bin/)
          riscv64-unknown-elf-gcc --version

      # Build bitstream
      - name: Build bitstream and bios
        run: |
          export PATH=$PATH:$(echo $PWD/../riscv64-*/bin/)
          source env/bin/activate
          ls $PWD/../riscv64-*/bin/
          riscv64-unknown-elf-gcc --version
          make bitstream

      # Build FPGA app
      - name: Build app
        run: |
          export PATH=$PATH:$(echo $PWD/../riscv64-*/bin/)
          source env/bin/activate
          make app
